### PR TITLE
Add Chapel language and runner

### PR DESCRIPTION
**Pull request by riftEmber**
To be merged after https://github.com/attempt-this-online/languages/pull/24.

Did not test locally as I was unable to get the install script working on my Archlinux VM; if necessary I can put more time into figuring that out, but I think given the simplicity of the runner it is not needed 🤞

### CODE REVIEW

**Comment by pxeger** [comment]
Will test tomorrow morning

**Comment by pxeger** [comment]
How exactly did the setup script fail? I'm testing it myself so as you say it's not crucial but I'd like to make sure it works properly

**Comment by pxeger** [comment]
Ok I got it working (c.f. 1747680a65945e10b52b0be5b1903a74609cab70). You can test it out on [staging](https://staging.ato.pxeger.com/run?L=chapel). The frontend there seems to be broken for some reason though - open devtools and follow the websocket stream to see it working

**Comment by riftEmber** [comment]
Setup script failed with `install: cannot stat 'invoke': No such file or directory`, presumably from [line 58](https://github.com/attempt-this-online/attempt-this-online/blob/main/setup/setup#L58). I used a VM image from linuxvmimages.com to avoid the Arch install process, so I would suspect their image of being non-standard before suspecting an actual problem with the setup script.

**Comment by riftEmber** [comment]
Hm, doesn't seem to work for me. Watching network tab in devtools, the execute request hangs indefinitely for [an example](https://staging.ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhYbyosyS1Jz8jSUEotT0pQ0rSHCUFmYKgA) that should compile and execute in around 10 seconds. Also occurs for [another example](https://staging.ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhaLKqwhDCgfJg4A) for which compilation should fail. Same result in Firefox and Chromium.

**Comment by pxeger** [comment]
About the setup script, that's is apparently just because `invoke` is missing from the build. That should be fixed when I next make a release

And sorry, I think staging is just pretty broken at the moment. The runner itself seems to be working though! I'll redeploy the production instance soon(™), and then you should be able to use it with no issues.

**Comment by riftEmber** [comment]
Makes sense, thank you!

**Pull request merged**
