### PR TITLE
Added langs.md as separate file instead of issue

### PR DESCRIPTION
**Pull request by AviFS**
Leaving comments on an issue will get messy fast and impossible to find & see stuff. Plus impossible to organize! We can easily refactor this in an external editor to sort it in alphabetical order whenever it starts getting unwieldy!

### CODE REVIEW

**Comment by pxeger** [comment]
Issues are for project management, the repository is for code.

I want to use GitHub task lists (which look like this:
- [ ] unchecked task
- [x] checked task

) because they have buttons to quickly create issues from items.

**Comment by AviFS** [comment]
It's a little too late, but we can have two subheadings: **Done** & **Almost**!

Each list will be sorted alphabetically every now and then. And when we add one, we check the box and move it up to the **Done** section. So it should really be:

# ATO Langs

Add a line or two with your favorite languages!

## Done
- [x] Jelly
- [x] Python
- [x] Python 2
- [x] Zsh

## Almost
- [ ] Scala
- [ ] Vyxal

**Comment by pxeger** [comment]
The workflow will look like this:
1. person adds language to a task list
2. project maintainer can extract a task list item into an issue when it's checked that it's not a duplicate
3. from then on, tracking of language itself can be done using that issue, for example by assigning it to someone, adding labels, or moving it around the columns on [the project board](https://github.com/attempt-this-online/attempt-this-online/projects/1)

**Comment by pxeger** [comment]
Also,
> Leaving comments on an issue will get messy fast

messier than having to open a new PR every time someone wants to add a request to the list? That just sounds like opening an issue with extra steps

**Pull request closed without merging**
