### PR TITLE
Add 05AB1E

### PR DESCRIPTION
**Pull request by Steffan153**
Not tested, so hopefully this works

### CODE REVIEW

**Comment by pxeger** [comment]
Looks good to me, I don't think this needs testing because I can't see it going wrong<sup>famous last words?</sup>.

**Comment by pxeger** [comment]
> famous last words

https://staging.ato.pxeger.com/run?1=m73MwDQxyTB1wYKlpSVpuhYLtZcUJyUXQ3nLos10FMxjoTwA

**Comment by Steffan153** [comment]
The input doesn't work either

**Comment by pxeger** [comment]
I think I broke something with ATO itself, because stdin doesn't work for any language...

**Comment by Steffan153** [comment]
Command line arguments do work, though:
https://staging.ato.pxeger.com/run?1=m73MwDQxyTB1wYKlpSVpuhYLtZcUJyUXQ3mro5V0dVNSk0rTlWIXG3OZQUQB

**Comment by pxeger** [comment]
Fixed it: https://staging.ato.pxeger.com/run?1=m73MwDQxyTB1wYKlpSVpuhaLDRW0lxQnJRdD-QsWGkEYAA

**Pull request merged**
