### PR TITLE
Add Thunno 2

### PR DESCRIPTION
**Pull request by nayakrujul**
Let me know if there's anything else I need to do.

### CODE REVIEW

**Comment by pxeger** [comment]
Thank you for marking your runner executable! Noone ever gets that right!

**Comment by jfioasd** [comment]
How in the world did you manage to upload an executable runner?

**Comment by nayakrujul** [comment]
@jfioasd I just copied the Thunno runner and edited it in TextEdit. Then I pushed it to GitHub in the command line.

**Comment by pxeger** [comment]
If you copy an existing runner it will be marked executable by default. Otherwise on Linux use `chmod +x runners/whatever`. Idk how to do it on Windows

**Comment by jfioasd** [comment]
Ah, so you need to use git to do this.

**Pull request merged**
