### PR TITLE
Add class to HTML for syntax highlighting

### PR DESCRIPTION
**Pull request by ysthakur**
Added `class="language-${languageName}"` so that syntax highlighting will hopefully work. Adding a link to the language's website would be nice, but I don't know how to do that or if that would be easy.

Btw, I feel like the `Copied to clipboard!` notification should be sent after it's actually copied, but that's a PR for another day.

### CODE REVIEW

**Comment by pxeger** [comment]
Sorry, I've already said I'm not adding syntax highlighting. See #21

**Comment by ysthakur** [comment]
@pxeger That issue's about syntax highlighting for ATO itself. This is so that submissions will have syntax highlighting when viewed on SE (and probably other sites). I don't think it's such a big deal, since ATO doesn't have to do any highlighting itself or import any libraries.

**Comment by pxeger** [comment]
Oh I see

**Comment by pxeger** [comment]
I think we should add a separate metadata field for SE syntax highlighting actually, so that languages with:
- no SE highlighting support
- different names on SE compared to their ATO names

...don't get weird `langauge-` classes added to them

and languages with no SE highlighting support but where a very similar language exists and has support can have the nearest one attached (e.g. Zsh gets `sh` on TIO)

**Comment by ysthakur** [comment]
Would that require a separate JSON file with `language: highlightName` mappings?

**Comment by pxeger** [comment]
No, I can just add a field to the runner files, like `#:SE_class: python`, in the same way I've done all other metadata

**Pull request merged**
