### PR TITLE
Fix Whitespace

### PR DESCRIPTION
**Pull request by Steffan153**
[it doesn't work rn](https://staging.ato.pxeger.com/run?1=m72qPCOzJLW4IDE5dcGCpaUlaboWNycpKChwKShwcgIxEIKZnJxASgFCQNkwRZzIqjmhqlEUgfRBdcKUglRygSSBkBNmLsQATqhFQBmQEqA6Li6Iy6AOhDkUAA).

[Charcoal doesn't work either.](https://staging.ato.pxeger.com/run?1=m70iOSOxKDk_MWfBgqWlJWm6Fks9UnNy8pcUJyUXQ0VgMgA) (I don't know why, the Docker container works on my computer.)

### CODE REVIEW

**Comment by pxeger** [comment]
I found Charcoal to not be working a while ago, for reasons I also didn't and don't understand. But thanks for the Whitespace fix

**Comment by Steffan153** [comment]
...Weird, Whitespace still doesn't work.

**Comment by pxeger** [comment]
Found the problem: it was Windows line endings.

Please run

```
git config --global core.autocrlf=true
```

and/or configure your text editor to use standard Unix-style `LF` line endings.

**Comment by pxeger** [comment]
Apparently, I already fixed these for you last week in https://github.com/Steffan153/attempt-this-online/commit/7d87215b21e46c2ad86fdf3b1bab31b7ccc3d2b3 but neglected to inform you of the problem, and also ended up deploying the un-fixed version.

**Pull request merged**
